### ISSUE TITLE
Deck editor allows 9 Harpie Lady in the deck.

### ISSUE THREAD

**Issue by jrmsweitzer** [AustinMCrane/yugiohspeedduels-support#17]
![Screenshot_20190605-054551](https://user-images.githubusercontent.com/8965310/58947134-4fa9aa80-8755-11e9-8b5c-4d8636ed08de.jpg)

You'll need to add Aliases to the cards and check on alias rather than name when adding to the deck.

**Comment by AustinMCrane** [comment]
this should be fixed
