### ISSUE TITLE
Login - invalid username/password combination should alert user

### ISSUE THREAD

**Issue by jrmsweitzer** [AustinMCrane/yugiohspeedduels-support#2]
An invalid username/password combination should let the user know the combination was not accepted. Currently there is no message to the user at all, giving the appearance of a broken login function.

**Comment by AustinMCrane** [comment]
![image](https://user-images.githubusercontent.com/12687588/57887267-b2fa8980-77f4-11e9-9f10-2caa45978c7d.png)
i fixed this over lunch thanks!
