### ISSUE TITLE
/decks - owner should be able to remove their own submitted decks

### ISSUE THREAD

**Issue by jrmsweitzer** [AustinMCrane/yugiohspeedduels-support#3]
When arriving at /decks, a logged-in user should see buttons next to individuals decks of their own to modify or delete that given deck.

**Comment by jrmsweitzer** [comment]
Looking at this, it's more of a FEATURE REQUEST than a bug. Have no idea how to edit the name, however.

**Comment by AustinMCrane** [comment]
added feature with may 28th release
