### ISSUE TITLE
/deck - some fusion monsters are placed into the main deck

### ISSUE THREAD

**Issue by jrmsweitzer** [AustinMCrane/yugiohspeedduels-support#4]
On the deck builder screen, when a user adds in either of the following fusion monsters, the fusion monsters themselves end up in the main deck, rather than the expected fusion deck.

- Arcana Knight Joker
- Alligator's Sword Dragon

**Comment by AustinMCrane** [comment]
this is fixed. but there does seem to be an issue with my data scraper process that gets this data.
<img width="1101" alt="Screen Shot 2019-05-16 at 5 29 20 PM" src="https://user-images.githubusercontent.com/12687588/57891230-47b6b480-7800-11e9-9531-b6e87a5b0754.png">
