### ISSUE TITLE
/deck - Main deck allows more than 1 skill, multiple copies of the same skill

### ISSUE THREAD

**Issue by jrmsweitzer** [AustinMCrane/yugiohspeedduels-support#9]
On the deck builder screen, a user is currently able to add in up to 3 copies of multiple skills at once to the main deck. There should only ever be one active skill at a time.

**Comment by AustinMCrane** [comment]
this should be fixed with the may 28th release

<img width="1622" alt="Screen Shot 2019-05-28 at 8 10 08 AM" src="https://user-images.githubusercontent.com/12687588/58480493-156e5680-8120-11e9-994f-309a04e6ed88.png">
